language: objective-c
osx_image: xcode8.3

cache:
  - bundler

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

script:
  - cd ios && bundle exec fastlane ios beta
