language: objective-c
osx_image: xcode8.3

cache:
  - bundler

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - npm install
  - cd ios

script:
  - bundle exec fastlane ios beta
