language: node_js

node_js:
  - '8'

os: osx
osx_image: xcode9.4

cache:
  - bundler

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - rvm install 2.2.2
  - cd ios

script:
  - bundle exec fastlane ios beta
