language: node_js

node_js:
  - '10'

os: osx
osx_image: xcode9.4

cache:
  - bundler

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc

before_script:
  - cd ios
  - gem install bundler
  - bundle install
script:
  - bundle exec fastlane ios beta

notifications:
  slack:
    rooms:
      - "$SLACK_NOTIFICATION_TOKEN"
    template:
      - "%{repository_slug} (%{commit}): Deploy to Test Flight by %{author} %{result}
        after %{duration}"
env:
  global:
    secure: ovVBNKQFwOCDDqIrxVx34Pg/kGpOGnlcblA6iEMMs8oucCqeuu3nQPNvY0Y3IqNGf8cETsyl05YFYWnsk6HIKKGK67Z2EFP5jVvFes6e7lJBqZJJp4qEhaNGTxSf6+Y8RUBTUniDNB2va9vYzSN3s9KHYTgnWUNbiU+X83Qpc3qaau2JY/4iimluZCjCZFQmpuq3u9iL/ywxBKu6nR1LUn5FGQeGQjIZhKT8latmjeYvvpQPsQUVK0bo0SFXHDO73wpazqzUcwSgrtKXiN4UMvuynOC6XnGeLG5z1fYz9vLvwZZzAYRNuwUIkdxB52zT7dPOk8qdbGCnsDOP9ZIIpu1LC1c19Y45aERmRwLuyTdl/4oJYPVdbKktSXAchYFhogqS6LFXOvqkuoXB1t4h4drvi3UpihxzlwRj8rc9VrAXJVKUthXi0JPY7W36T+7IOx3e7/paxVgP1xf/gLu2lbXYpd6mGAf5G669WVmArSEedltwUttCFuhjMMwwInsHUDw0m7ieeo2G5nmpYaq0i3mlhRDzPHrvYIEN5WZv8uLC4WgJDM6ZoBgj4/EjXu6etB9+S8gD9qapaCXlL2mHP55Rns1kqGvFDG4TCKfy5dpU5gnuPxUFekF/bsTFAXLQY425C8eCsCDPWTJFOrxzeclFK1/NQfvjkruCC4C5dTk=
