# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'thekeymobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for thekeymobile
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'Core', 'DevSupport', 'RCTText', 'RCTImage', 'RCTNetwork', 'RCTWebSocket', ]



  platform :ios, '9.0'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'thekeymobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'thekeymobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for thekeymobile-tvOS

  target 'thekeymobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
