# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do |lane, options|
    setup_travis
  end

  desc "Push a new beta build to TestFlight" 
  lane :beta do
    sh("npm", "run", "bundle-ios")
    match(
      type: "appstore",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )
    version = get_version_number(target: "thekeymobile")
    latestBuildNumber = latest_testflight_build_number(version: "#{version}")
    increment_build_number(
      xcodeproj: "thekeymobile.xcodeproj",
      build_number: latestBuildNumber + 1
    )
    gym(
      workspace: "thekeymobile.xcworkspace",
      scheme: "thekeymobile",
      clean: true
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
